#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum Instr {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,

    None,
}

impl Instr {
    pub fn name(self) -> &'static str {
        match self {
            Instr::ADC => "ADC",
            Instr::AND => "AND",
            Instr::ASL => "ASL",
            Instr::BCC => "BCC",
            Instr::BCS => "BCS",
            Instr::BEQ => "BEQ",
            Instr::BIT => "BIT",
            Instr::BMI => "BMI",
            Instr::BNE => "BNE",
            Instr::BPL => "BPL",
            Instr::BRK => "BRK",
            Instr::BVC => "BVC",
            Instr::BVS => "BVS",
            Instr::CLC => "CLC",
            Instr::CLD => "CLD",
            Instr::CLI => "CLI",
            Instr::CLV => "CLV",
            Instr::CMP => "CMP",
            Instr::CPX => "CPX",
            Instr::CPY => "CPY",
            Instr::DEC => "DEC",
            Instr::DEX => "DEX",
            Instr::DEY => "DEY",
            Instr::EOR => "EOR",
            Instr::INC => "INC",
            Instr::INX => "INX",
            Instr::INY => "INY",
            Instr::JMP => "JMP",
            Instr::JSR => "JSR",
            Instr::LDA => "LDA",
            Instr::LDX => "LDX",
            Instr::LDY => "LDY",
            Instr::LSR => "LSR",
            Instr::NOP => "NOP",
            Instr::ORA => "ORA",
            Instr::PHA => "PHA",
            Instr::PHP => "PHP",
            Instr::PLA => "PLA",
            Instr::PLP => "PLP",
            Instr::ROL => "ROL",
            Instr::ROR => "ROR",
            Instr::RTI => "RTI",
            Instr::RTS => "RTS",
            Instr::SBC => "SBC",
            Instr::SEC => "SEC",
            Instr::SED => "SED",
            Instr::SEI => "SEI",
            Instr::STA => "STA",
            Instr::STX => "STX",
            Instr::STY => "STY",
            Instr::TAX => "TAX",
            Instr::TAY => "TAY",
            Instr::TSX => "TSX",
            Instr::TXA => "TXA",
            Instr::TXS => "TXS",
            Instr::TYA => "TYA",
            Instr::None => unreachable!(),
        }
    }
}

pub fn m6502_instr_table<M: crate::Memory>() -> &'static [(Instr, crate::addressing_mode::AM, fn(&mut crate::R6502<M>, crate::addressing_mode::AM))] {
    &[
        (Instr::BRK,  crate::addressing_mode::AM::IMPL, crate::instr::brk),
        (Instr::ORA,  crate::addressing_mode::AM::XIZI, crate::instr::ora),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ORA,  crate::addressing_mode::AM::ZP,   crate::instr::ora),
        (Instr::ASL,  crate::addressing_mode::AM::ZP,   crate::instr::asl),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::PHP,  crate::addressing_mode::AM::IMPL, crate::instr::php),
        (Instr::ORA,  crate::addressing_mode::AM::IM,   crate::instr::ora),
        (Instr::ASL,  crate::addressing_mode::AM::ACC,  crate::instr::asl),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ORA,  crate::addressing_mode::AM::ABS,  crate::instr::ora),
        (Instr::ASL,  crate::addressing_mode::AM::ABS,  crate::instr::asl),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BPL,  crate::addressing_mode::AM::REL,  crate::instr::bpl),
        (Instr::ORA,  crate::addressing_mode::AM::ZIYI, crate::instr::ora),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ORA,  crate::addressing_mode::AM::XIZ,  crate::instr::ora),
        (Instr::ASL,  crate::addressing_mode::AM::XIZ,  crate::instr::asl),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CLC,  crate::addressing_mode::AM::IMPL, crate::instr::clc),
        (Instr::ORA,  crate::addressing_mode::AM::YIA,  crate::instr::ora),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ORA,  crate::addressing_mode::AM::XIA,  crate::instr::ora),
        (Instr::ASL,  crate::addressing_mode::AM::XIA,  crate::instr::asl),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::JSR,  crate::addressing_mode::AM::ABS,  crate::instr::jsr),
        (Instr::AND,  crate::addressing_mode::AM::XIZI, crate::instr::and),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BIT,  crate::addressing_mode::AM::ZP,   crate::instr::bit),
        (Instr::AND,  crate::addressing_mode::AM::ZP,   crate::instr::and),
        (Instr::ROL,  crate::addressing_mode::AM::ZP,   crate::instr::rol),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::PLP,  crate::addressing_mode::AM::IMPL, crate::instr::plp),
        (Instr::AND,  crate::addressing_mode::AM::IM,   crate::instr::and),
        (Instr::ROL,  crate::addressing_mode::AM::ACC,  crate::instr::rol),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BIT,  crate::addressing_mode::AM::ABS,  crate::instr::bit),
        (Instr::AND,  crate::addressing_mode::AM::ABS,  crate::instr::and),
        (Instr::ROL,  crate::addressing_mode::AM::ABS,  crate::instr::rol),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BMI,  crate::addressing_mode::AM::REL,  crate::instr::bmi),
        (Instr::AND,  crate::addressing_mode::AM::ZIYI, crate::instr::and),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::AND,  crate::addressing_mode::AM::XIZ,  crate::instr::and),
        (Instr::ROL,  crate::addressing_mode::AM::XIZ,  crate::instr::rol),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::SEC,  crate::addressing_mode::AM::IMPL, crate::instr::sec),
        (Instr::AND,  crate::addressing_mode::AM::YIA,  crate::instr::and),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::AND,  crate::addressing_mode::AM::XIA,  crate::instr::and),
        (Instr::ROL,  crate::addressing_mode::AM::XIA,  crate::instr::rol),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::RTI,  crate::addressing_mode::AM::IMPL, crate::instr::rti),
        (Instr::EOR,  crate::addressing_mode::AM::XIZI, crate::instr::eor),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::EOR,  crate::addressing_mode::AM::ZP,   crate::instr::eor),
        (Instr::LSR,  crate::addressing_mode::AM::ZP,   crate::instr::lsr),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::PHA,  crate::addressing_mode::AM::IMPL, crate::instr::pha),
        (Instr::EOR,  crate::addressing_mode::AM::IM,   crate::instr::eor),
        (Instr::LSR,  crate::addressing_mode::AM::ACC,  crate::instr::lsr),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::JMP,  crate::addressing_mode::AM::ABS,  crate::instr::jmp),
        (Instr::EOR,  crate::addressing_mode::AM::ABS,  crate::instr::eor),
        (Instr::LSR,  crate::addressing_mode::AM::ABS,  crate::instr::lsr),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BVC,  crate::addressing_mode::AM::REL,  crate::instr::bvc),
        (Instr::EOR,  crate::addressing_mode::AM::ZIYI, crate::instr::eor),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::EOR,  crate::addressing_mode::AM::XIZ,  crate::instr::eor),
        (Instr::LSR,  crate::addressing_mode::AM::XIZ,  crate::instr::lsr),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CLI,  crate::addressing_mode::AM::IMPL, crate::instr::cli),
        (Instr::EOR,  crate::addressing_mode::AM::YIA,  crate::instr::eor),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::EOR,  crate::addressing_mode::AM::XIA,  crate::instr::eor),
        (Instr::LSR,  crate::addressing_mode::AM::XIA,  crate::instr::lsr),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::RTS,  crate::addressing_mode::AM::IMPL, crate::instr::rts),
        (Instr::ADC,  crate::addressing_mode::AM::XIZI, crate::instr::adc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ADC,  crate::addressing_mode::AM::ZP,   crate::instr::adc),
        (Instr::ROR,  crate::addressing_mode::AM::ZP,   crate::instr::ror),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::PLA,  crate::addressing_mode::AM::IMPL, crate::instr::pla),
        (Instr::ADC,  crate::addressing_mode::AM::IM,   crate::instr::adc),
        (Instr::ROR,  crate::addressing_mode::AM::ACC,  crate::instr::ror),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::JMP,  crate::addressing_mode::AM::ABSI, crate::instr::jmp),
        (Instr::ADC,  crate::addressing_mode::AM::ABS,  crate::instr::adc),
        (Instr::ROR,  crate::addressing_mode::AM::ABS,  crate::instr::ror),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BVS,  crate::addressing_mode::AM::REL,  crate::instr::bvs),
        (Instr::ADC,  crate::addressing_mode::AM::ZIYI, crate::instr::adc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ADC,  crate::addressing_mode::AM::XIZ,  crate::instr::adc),
        (Instr::ROR,  crate::addressing_mode::AM::XIZ,  crate::instr::ror),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::SEI,  crate::addressing_mode::AM::IMPL, crate::instr::sei),
        (Instr::ADC,  crate::addressing_mode::AM::YIA,  crate::instr::adc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::ADC,  crate::addressing_mode::AM::XIA,  crate::instr::adc),
        (Instr::ROR,  crate::addressing_mode::AM::XIA,  crate::instr::ror),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::STA,  crate::addressing_mode::AM::XIZI, crate::instr::sta),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::STY,  crate::addressing_mode::AM::ZP,   crate::instr::sty),
        (Instr::STA,  crate::addressing_mode::AM::ZP,   crate::instr::sta),
        (Instr::STX,  crate::addressing_mode::AM::ZP,   crate::instr::stx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::DEY,  crate::addressing_mode::AM::IMPL, crate::instr::dey),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::TXA,  crate::addressing_mode::AM::IMPL, crate::instr::txa),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::STY,  crate::addressing_mode::AM::ABS,  crate::instr::sty),
        (Instr::STA,  crate::addressing_mode::AM::ABS,  crate::instr::sta),
        (Instr::STX,  crate::addressing_mode::AM::ABS,  crate::instr::stx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BCC,  crate::addressing_mode::AM::REL,  crate::instr::bcc),
        (Instr::STA,  crate::addressing_mode::AM::ZIYI, crate::instr::sta),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::STY,  crate::addressing_mode::AM::XIZ,  crate::instr::sty),
        (Instr::STA,  crate::addressing_mode::AM::XIZ,  crate::instr::sta),
        (Instr::STX,  crate::addressing_mode::AM::YIZ,  crate::instr::stx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::TYA,  crate::addressing_mode::AM::IMPL, crate::instr::tya),
        (Instr::STA,  crate::addressing_mode::AM::YIA,  crate::instr::sta),
        (Instr::TXS,  crate::addressing_mode::AM::IMPL, crate::instr::txs),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::STA,  crate::addressing_mode::AM::XIA,  crate::instr::sta),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::LDY,  crate::addressing_mode::AM::IM,   crate::instr::ldy),
        (Instr::LDA,  crate::addressing_mode::AM::XIZI, crate::instr::lda),
        (Instr::LDX,  crate::addressing_mode::AM::IM,   crate::instr::ldx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::LDY,  crate::addressing_mode::AM::ZP,   crate::instr::ldy),
        (Instr::LDA,  crate::addressing_mode::AM::ZP,   crate::instr::lda),
        (Instr::LDX,  crate::addressing_mode::AM::ZP,   crate::instr::ldx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::TAY,  crate::addressing_mode::AM::IMPL, crate::instr::tay),
        (Instr::LDA,  crate::addressing_mode::AM::IM,   crate::instr::lda),
        (Instr::TAX,  crate::addressing_mode::AM::IMPL, crate::instr::tax),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::LDY,  crate::addressing_mode::AM::ABS,  crate::instr::ldy),
        (Instr::LDA,  crate::addressing_mode::AM::ABS,  crate::instr::lda),
        (Instr::LDX,  crate::addressing_mode::AM::ABS,  crate::instr::ldx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BCS,  crate::addressing_mode::AM::REL,  crate::instr::bcs),
        (Instr::LDA,  crate::addressing_mode::AM::ZIYI, crate::instr::lda),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::LDY,  crate::addressing_mode::AM::XIZ,  crate::instr::ldy),
        (Instr::LDA,  crate::addressing_mode::AM::XIZ,  crate::instr::lda),
        (Instr::LDX,  crate::addressing_mode::AM::YIZ,  crate::instr::ldx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CLV,  crate::addressing_mode::AM::IMPL, crate::instr::clv),
        (Instr::LDA,  crate::addressing_mode::AM::YIA,  crate::instr::lda),
        (Instr::TSX,  crate::addressing_mode::AM::IMPL, crate::instr::tsx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::LDY,  crate::addressing_mode::AM::XIA,  crate::instr::ldy),
        (Instr::LDA,  crate::addressing_mode::AM::XIA,  crate::instr::lda),
        (Instr::LDX,  crate::addressing_mode::AM::YIA,  crate::instr::ldx),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CPY,  crate::addressing_mode::AM::IM,   crate::instr::cpy),
        (Instr::CMP,  crate::addressing_mode::AM::XIZI, crate::instr::cmp),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CPY,  crate::addressing_mode::AM::ZP,   crate::instr::cpy),
        (Instr::CMP,  crate::addressing_mode::AM::ZP,   crate::instr::cmp),
        (Instr::DEC,  crate::addressing_mode::AM::ZP,   crate::instr::dec),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::INY,  crate::addressing_mode::AM::IMPL, crate::instr::iny),
        (Instr::CMP,  crate::addressing_mode::AM::IM,   crate::instr::cmp),
        (Instr::DEX,  crate::addressing_mode::AM::IMPL, crate::instr::dex),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CPY,  crate::addressing_mode::AM::ABS,  crate::instr::cpy),
        (Instr::CMP,  crate::addressing_mode::AM::ABS,  crate::instr::cmp),
        (Instr::DEC,  crate::addressing_mode::AM::ABS,  crate::instr::dec),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BNE,  crate::addressing_mode::AM::REL,  crate::instr::bne),
        (Instr::CMP,  crate::addressing_mode::AM::ZIYI, crate::instr::cmp),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CMP,  crate::addressing_mode::AM::XIZ,  crate::instr::cmp),
        (Instr::DEC,  crate::addressing_mode::AM::XIZ,  crate::instr::dec),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CLD,  crate::addressing_mode::AM::IMPL, crate::instr::cld),
        (Instr::CMP,  crate::addressing_mode::AM::YIA,  crate::instr::cmp),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CMP,  crate::addressing_mode::AM::XIA,  crate::instr::cmp),
        (Instr::DEC,  crate::addressing_mode::AM::XIA,  crate::instr::dec),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CPX,  crate::addressing_mode::AM::IM,   crate::instr::cpx),
        (Instr::SBC,  crate::addressing_mode::AM::XIZI, crate::instr::sbc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CPX,  crate::addressing_mode::AM::ZP,   crate::instr::cpx),
        (Instr::SBC,  crate::addressing_mode::AM::ZP,   crate::instr::sbc),
        (Instr::INC,  crate::addressing_mode::AM::ZP,   crate::instr::inc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::INX,  crate::addressing_mode::AM::IMPL, crate::instr::inx),
        (Instr::SBC,  crate::addressing_mode::AM::IM,   crate::instr::sbc),
        (Instr::NOP,  crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::CPX,  crate::addressing_mode::AM::ABS,  crate::instr::cpx),
        (Instr::SBC,  crate::addressing_mode::AM::ABS,  crate::instr::sbc),
        (Instr::INC,  crate::addressing_mode::AM::ABS,  crate::instr::inc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::BEQ,  crate::addressing_mode::AM::REL,  crate::instr::beq),
        (Instr::SBC,  crate::addressing_mode::AM::ZIYI, crate::instr::sbc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::SBC,  crate::addressing_mode::AM::XIZ,  crate::instr::sbc),
        (Instr::INC,  crate::addressing_mode::AM::XIZ,  crate::instr::inc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::SED,  crate::addressing_mode::AM::IMPL, crate::instr::sed),
        (Instr::SBC,  crate::addressing_mode::AM::YIA,  crate::instr::sbc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
        (Instr::SBC,  crate::addressing_mode::AM::XIA,  crate::instr::sbc),
        (Instr::INC,  crate::addressing_mode::AM::XIA,  crate::instr::inc),
        (Instr::None, crate::addressing_mode::AM::IMPL, crate::instr::nop),
    ]
}

